### PR TITLE
feat: migrate to IsaacLab

### PR DESCRIPTION
**Pull request by fan-ziqi**
Please configure according to the README

Use https://github.com/fan-ziqi/viplanner_isaaclab_exts instead of https://github.com/pascal-roth/orbit_envs

#27

### CODE REVIEW

**Comment by fan-ziqi** [comment]
I‘ve found the changelog in `0.13.0 (2024-03-12)`

> Fixed the return shape of colored images for segmentation data types inside the [omni.isaac.lab.sensors.Camera](https://docs.robotsfan.com/isaaclab/source/api/lab/omni.isaac.lab.sensors.html#omni.isaac.lab.sensors.Camera) class. Earlier, the images were always returned as `int32`. Now, they are casted to `uint8` 4-channel array before returning if colorization is enabled for the annotation type.

It should be this change that caused the problem

**Comment by fan-ziqi** [comment]
After setting colorize_semantic_segmentation to False in semantic_camera cfg, this leads to a new bug

```
Traceback (most recent call last):
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/standalone/viplanner_demo.py", line 153, in <module>
    main()
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/standalone/viplanner_demo.py", line 73, in main
    env = ManagerBasedRLEnv(env_cfg)
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 75, in __init__
    super().__init__(cfg=cfg)
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_env.py", line 136, in __init__
    self.load_managers()
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 115, in load_managers
    super().load_managers()
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_env.py", line 213, in load_managers
    self.observation_manager = ObservationManager(self.cfg.observations, self)
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 69, in __init__
    super().__init__(cfg, env)
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/manager_base.py", line 130, in __init__
    self._prepare_terms()
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 337, in _prepare_terms
    obs_dims = tuple(term_cfg.func(self._env, **term_cfg.params).shape)
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/extension/omni.viplanner/omni/viplanner/viplanner/mdp/observations.py", line 92, in isaac_camera_data
    return output.permute(0, 3, 1, 2)
RuntimeError: permute(sparse_coo): number of dimensions in the tensor input does not match the length of the desired ordering of dimensions i.e. input.dim() = 5 is not equal to len(dims) = 4
```

**Comment by fan-ziqi** [comment]
https://github.com/leggedrobotics/viplanner/pull/28#issuecomment-2418420294 has fixed by https://github.com/leggedrobotics/viplanner/pull/28/commits/3a85d17beafd683fe89f61c3285d0efe30d26cd0

**Comment by fan-ziqi** [comment]
After the above modifications, it seems that Carla's sample program can run properly, but it crashes after a few seconds.

Snipaste_2024-10-17_12-25-53

```
[INFO]: Completed setting up the environment...
2024-10-17 04:25:39 [23,552ms] [Warning] [omni.isaac.lab.sensors.camera.camera] Camera aperture offsets are not supported by Omniverse. These parameters are ignored.
2024-10-17 04:25:39 [23,552ms] [Warning] [omni.isaac.lab.sensors.camera.camera] Camera aperture offsets are not supported by Omniverse. These parameters are ignored.
/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/extension/omni.viplanner/omni/viplanner/viplanner/viplanner_algo.py:90: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  model_state_dict, _ = torch.load(os.path.join(model_dir, "model.pt"))
/home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/site-packages/torch/nn/modules/module.py:1562: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at ../aten/src/ATen/native/cudnn/RNN.cpp:1424.)
  return forward_call(*args, **kwargs)
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [9,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [10,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [11,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/standalone/viplanner_demo.py", line 153, in <module>
    main()
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/standalone/viplanner_demo.py", line 123, in main
    obs = env.step(action=paths.view(paths.shape[0], -1))[0]
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 208, in step
    self.obs_buf = self.observation_manager.compute()
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 195, in compute
    obs_buffer[group_name] = self.compute_group(group_name)
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 247, in compute_group
    obs: torch.Tensor = term_cfg.func(self._env, **term_cfg.params).clone()
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/extension/omni.viplanner/omni/viplanner/viplanner/mdp/observations.py", line 93, in cam_position
    sensor: CameraData = env.scene.sensors[sensor_cfg.name].data
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/camera/camera.py", line 174, in data
    self._update_outdated_buffers()
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/sensor_base.py", line 284, in _update_outdated_buffers
    outdated_env_ids = self._is_outdated.nonzero().squeeze(-1)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 328
2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 331
2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 334
2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 337
2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 340
2024-10-17 04:25:56 [40,609ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
2024-10-17 04:25:56 [40,609ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
2024-10-17 04:25:56 [40,611ms] [Warning] [omni.physx.plugin] PhysX warning: /builds/omniverse/physics/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp, FILE /builds/omniverse/physics/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp, LINE 167
2024-10-17 04:25:56 [40,612ms] [Error] [omni.physx.plugin] PhysX error: Failed to unload CUDA module data, returned 710., FILE /builds/omniverse/physics/physx/source/cudamanager/src/CudaContextManager.cpp, LINE 817
2024-10-17 04:25:56 [40,702ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
```

**Comment by fan-ziqi** [comment]
Warehouse works perfectly!

https://github.com/user-attachments/assets/b9e72b43-75e4-42c0-b3f6-5c033875ce7b

**Comment by fan-ziqi** [comment]
The extension can't work in IsaacLab https://github.com/fan-ziqi/isaaclab_envs

**Comment by pascal-roth** [comment]
> The extension can't work in IsaacLab https://github.com/fan-ziqi/isaaclab_envs

Why can it not work?

**Comment by pascal-roth** [comment]
> After the above modifications, it seems that Carla's sample program can run properly, but it crashes after a few seconds.
> 
> Snipaste_2024-10-17_12-25-53
> 
> ```
> [INFO]: Completed setting up the environment...
> 2024-10-17 04:25:39 [23,552ms] [Warning] [omni.isaac.lab.sensors.camera.camera] Camera aperture offsets are not supported by Omniverse. These parameters are ignored.
> 2024-10-17 04:25:39 [23,552ms] [Warning] [omni.isaac.lab.sensors.camera.camera] Camera aperture offsets are not supported by Omniverse. These parameters are ignored.
> /home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/extension/omni.viplanner/omni/viplanner/viplanner/viplanner_algo.py:90: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
>   model_state_dict, _ = torch.load(os.path.join(model_dir, "model.pt"))
> /home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/site-packages/torch/nn/modules/module.py:1562: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at ../aten/src/ATen/native/cudnn/RNN.cpp:1424.)
>   return forward_call(*args, **kwargs)
> ../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [9,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
> ../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [10,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
> ../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [11,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
> Traceback (most recent call last):
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/standalone/viplanner_demo.py", line 153, in <module>
>     main()
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/standalone/viplanner_demo.py", line 123, in main
>     obs = env.step(action=paths.view(paths.shape[0], -1))[0]
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 208, in step
>     self.obs_buf = self.observation_manager.compute()
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 195, in compute
>     obs_buffer[group_name] = self.compute_group(group_name)
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 247, in compute_group
>     obs: torch.Tensor = term_cfg.func(self._env, **term_cfg.params).clone()
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/extension/omni.viplanner/omni/viplanner/viplanner/mdp/observations.py", line 93, in cam_position
>     sensor: CameraData = env.scene.sensors[sensor_cfg.name].data
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/camera/camera.py", line 174, in data
>     self._update_outdated_buffers()
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/sensor_base.py", line 284, in _update_outdated_buffers
>     outdated_env_ids = self._is_outdated.nonzero().squeeze(-1)
> RuntimeError: CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 328
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 331
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 334
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 337
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 340
> 2024-10-17 04:25:56 [40,609ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
> 2024-10-17 04:25:56 [40,609ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
> 2024-10-17 04:25:56 [40,611ms] [Warning] [omni.physx.plugin] PhysX warning: /builds/omniverse/physics/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp, FILE /builds/omniverse/physics/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp, LINE 167
> 2024-10-17 04:25:56 [40,612ms] [Error] [omni.physx.plugin] PhysX error: Failed to unload CUDA module data, returned 710., FILE /builds/omniverse/physics/physx/source/cudamanager/src/CudaContextManager.cpp, LINE 817
> 2024-10-17 04:25:56 [40,702ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
> ```

This seems like an index error. Typically, setting the device to `cpu` in IsaacLab lets you see directly where the issue is.

**Comment by pascal-roth** [comment]
I would try your changes now and see if I can also run the experiments with the latest IsaacLab version. Then I would merge both and introduce a tag for orbit and IsaacLab. Any issues that are still apparent from your side expect:

- index error in Carla
- missing textures in Carla

**Comment by fan-ziqi** [comment]
> I would try your changes now and see if I can also run the experiments with the latest IsaacLab version. Then I would merge both and introduce a tag for orbit and IsaacLab. Any issues that are still apparent from your side expect:
> 
> * index error in Carla
> * missing textures in Carla

I've test `Matterport-17DRP5sb8fy`, the robots can‘t walk normally

Matterport-17DRP5sb8fy

**Comment by pascal-roth** [comment]
> > > The extension can't work in IsaacLab https://github.com/fan-ziqi/isaaclab_envs
> > 
> > 
> > Why can it not work?
> 
> I think it's IsaacLab's bug, I've opened an issue here [isaac-sim/IsaacLabExtensionTemplate#39](https://github.com/isaac-sim/IsaacLabExtensionTemplate/issues/39) , the error is the same as the image in that issue

Typically, we don't have to activate the extensions in the GUI. Especially as we are running standalone scripts, the extensions are loaded per default and without an issue.

**Comment by pascal-roth** [comment]
> > I would try your changes now and see if I can also run the experiments with the latest IsaacLab version. Then I would merge both and introduce a tag for orbit and IsaacLab. Any issues that are still apparent from your side expect:
> > 
> > * index error in Carla
> > * missing textures in Carla
> 
> I've test `Matterport-17DRP5sb8fy`, the robots can‘t walk normally
> 
> Matterport-17DRP5sb8fy

Hm strange, the robot should still be able to move as in any other environment. Does it sink into the ground?

**Comment by fan-ziqi** [comment]
The following is README of `orbit_envs` . Do I need to modify it? Users are unable to load the extension according to the instructions below


## Usage

For the Matterport extension, a GUI interface is available. To use it, start the simulation:

```
./orbit.sh -s
```

Then, in the GUI, go to `Window -> Extensions` and type `Matterport` in the search bar. You should see the Matterport3D extension.
Enable it to open the GUI interface.

To use both as part of an Orbit workflow, please refer to the [ViPlanner Demo](https://github.com/leggedrobotics/viplanner/tree/main/omniverse).

**Comment by fan-ziqi** [comment]
> Hm strange, the robot should still be able to move as in any other environment. Does it sink into the ground?

No, there is still a collision between robot and ground. The robot will fall and then reset

**Comment by fan-ziqi** [comment]
BTW, I didn't test the training script because I don't know how to prepare the training data, it seems that there is no clear explanation in README

**Comment by fan-ziqi** [comment]
> > > > The extension can't work in IsaacLab https://github.com/fan-ziqi/isaaclab_envs
> > > 
> > > 
> > > Why can it not work?
> > 
> > 
> > I think it's IsaacLab's bug, I've opened an issue here [isaac-sim/IsaacLabExtensionTemplate#39](https://github.com/isaac-sim/IsaacLabExtensionTemplate/issues/39) , the error is the same as the image in that issue
> 
> Typically, we don't have to activate the extensions in the GUI. Especially as we are running standalone scripts, the extensions are loaded per default and without an issue.

Fixed in https://github.com/isaac-sim/IsaacLab/pull/1266

**Comment by fan-ziqi** [comment]
https://github.com/fan-ziqi/isaac_envs has renamed to https://github.com/fan-ziqi/viplanner_isaaclab_exts

**Comment by fan-ziqi** [comment]
https://github.com/pascal-roth/orbit_envs/blob/7350e7b599af9e0226d53a33c21be3d1a12552d5/extensions/omni.isaac.matterport/omni/isaac/matterport/scripts/matterport_ext.py#L445-L451

```
        camera_pattern_cfg = patterns.PinholeCameraPatternCfg(
            focal_length=24.0,
            horizontal_aperture=20.955,
            height=camera_height,
            width=camera_width,
            data_types=data_types,
        )
```

Seems that `PinholeCameraPatternCfg` don't have `data_types`

**Comment by heyshouzi** [comment]
> After the above modifications, it seems that Carla's sample program can run properly, but it crashes after a few seconds.经过上述修改后，看起来Carla的示例程序可以正常运行，但是几秒钟后就崩溃了。
> 
> Snipaste_2024-10-17_12-25-53
> 
> ```
> [INFO]: Completed setting up the environment...
> 2024-10-17 04:25:39 [23,552ms] [Warning] [omni.isaac.lab.sensors.camera.camera] Camera aperture offsets are not supported by Omniverse. These parameters are ignored.
> 2024-10-17 04:25:39 [23,552ms] [Warning] [omni.isaac.lab.sensors.camera.camera] Camera aperture offsets are not supported by Omniverse. These parameters are ignored.
> /home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/extension/omni.viplanner/omni/viplanner/viplanner/viplanner_algo.py:90: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
>   model_state_dict, _ = torch.load(os.path.join(model_dir, "model.pt"))
> /home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/site-packages/torch/nn/modules/module.py:1562: UserWarning: RNN module weights are not part of single contiguous chunk of memory. This means they need to be compacted at every call, possibly greatly increasing memory usage. To compact weights again call flatten_parameters(). (Triggered internally at ../aten/src/ATen/native/cudnn/RNN.cpp:1424.)
>   return forward_call(*args, **kwargs)
> ../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [9,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
> ../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [10,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
> ../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [2827,0,0], thread: [11,0,0] Assertion `-sizes[i] <= index && index < sizes[i] && "index out of bounds"` failed.
> Traceback (most recent call last):
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/standalone/viplanner_demo.py", line 153, in <module>
>     main()
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/standalone/viplanner_demo.py", line 123, in main
>     obs = env.step(action=paths.view(paths.shape[0], -1))[0]
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/envs/manager_based_rl_env.py", line 208, in step
>     self.obs_buf = self.observation_manager.compute()
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 195, in compute
>     obs_buffer[group_name] = self.compute_group(group_name)
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/managers/observation_manager.py", line 247, in compute_group
>     obs: torch.Tensor = term_cfg.func(self._env, **term_cfg.params).clone()
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/omniverse/extension/omni.viplanner/omni/viplanner/viplanner/mdp/observations.py", line 93, in cam_position
>     sensor: CameraData = env.scene.sensors[sensor_cfg.name].data
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/camera/camera.py", line 174, in data
>     self._update_outdated_buffers()
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sensors/sensor_base.py", line 284, in _update_outdated_buffers
>     outdated_env_ids = self._is_outdated.nonzero().squeeze(-1)
> RuntimeError: CUDA error: device-side assert triggered
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 328
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 331
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 334
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 337
> 2024-10-17 04:25:56 [40,606ms] [Error] [omni.physx.fabric.plugin] CUDA error: device-side assert triggered: ../../../extensions/runtime/source/omni.physx.fabric/plugins/DirectGpuHelper.cpp: 340
> 2024-10-17 04:25:56 [40,609ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Annotators' for removal
> 2024-10-17 04:25:56 [40,609ms] [Warning] [omni.graph.core.plugin] Could not find category 'Replicator:Core' for removal
> 2024-10-17 04:25:56 [40,611ms] [Warning] [omni.physx.plugin] PhysX warning: /builds/omniverse/physics/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp, FILE /builds/omniverse/physics/physx/source/gpucommon/src/PxgCudaMemoryAllocator.cpp, LINE 167
> 2024-10-17 04:25:56 [40,612ms] [Error] [omni.physx.plugin] PhysX error: Failed to unload CUDA module data, returned 710., FILE /builds/omniverse/physics/physx/source/cudamanager/src/CudaContextManager.cpp, LINE 817
> 2024-10-17 04:25:56 [40,702ms] [Warning] [carb] Recursive unloadAllPlugins() detected!
warehouse sample  program can run properly, but it crashes after a few seconds   in orbit_env  environment


https://github.com/user-attachments/assets/f31f6816-258c-4f32-a93e-47cd228231c7

**Comment by fan-ziqi** [comment]
> I would try your changes now and see if I can also run the experiments with the latest IsaacLab version. Then I would merge both and introduce a tag for orbit and IsaacLab. Any issues that are still apparent from your side expect:
> 
> * index error in Carla
> * missing textures in Carla

I ran Carla again, and the problem of missing texture disappeared. However, the robot seems to have crossed the ground and there seems to be an issue with the terrain

https://github.com/user-attachments/assets/6d43c064-2f86-4635-b289-d7058dccd694

Look forward to your reply

**Comment by pascal-roth** [comment]
> > I would try your changes now and see if I can also run the experiments with the latest IsaacLab version. Then I would merge both and introduce a tag for orbit and IsaacLab. Any issues that are still apparent from your side expect:
> > 
> > * index error in Carla
> > * missing textures in Carla
> 
> I ran Carla again, and the problem of missing texture disappeared. However, the robot seems to have crossed the ground and there seems to be an issue with the terrain
> 
>  bandicam.2024-10-19.13-18-43-818.mp4 
> Look forward to your reply

So I fixed the index issue on my end, was an inconsistency in the return values of the semantic camera of Isaac Sim. 

You see the ground penetration here because the Carla Mesh does not have collision shapes. The reason for that is that the public raycaster used for the height scan of the locomotion policy only supports a single mesh at this point. Carla is composed of many meshes. To get the correct height scan measurements, we set the ground at the height of the street and "ignore" the elevation of the sidewalk.

**Comment by fan-ziqi** [comment]
OK, I understand, is there anything else I need to change?

**Comment by pascal-roth** [comment]
@fan-ziqi I incorporated your changes with some more updates in #32 (including that I transferred the Matterport extension to be part of that repo to remove this double structure). Can you please check if your workflows still work with the changes done there? Then, I can merge it. 

Thanks again for your great work. 

Closing this PR now in favor of #32

**Pull request closed without merging**
