### PR TITLE
Upgrades the repo to the latest version of IsaacLab

### PR DESCRIPTION
**Pull request by pascal-roth**
# Description

This PR updates the code to the newer version of IsaacLab. Moreover, it removes the need for link the repo `orbit_envs`.

### CODE REVIEW

**Comment by pascal-roth** [comment]
@fan-ziqi I added your changes here along with some more updates. Please let me know if everything still works for you, then we can update and merge the repo. 

@heyshouzi if you merge this PR already in the local copy, everything should work and the locomotion policy should be found

**Comment by fan-ziqi** [comment]
Thank you for your approval. I will test your modifications now. and if everything works without errors, I will reply under this PR.

**Comment by fan-ziqi** [comment]
I noticed that you have already migrated my changes in the extension. I tested the entire demo process and encountered the following issues:
1. The extension for Carla hasn't been uploaded.
2. The problem of missing textures in Carla still exists, and the robot remains standing still after initialization
missing-textures
3. In Matterport env, the robot stuck here because of the desk, If I modify the init state(I change it to `robot.init_state.pos = (8.0, 0.0, 0.6)` ), it will be able to pass through the initial section of the route, but it crashes and falls near the end.
https://github.com/leggedrobotics/viplanner/blob/3bea1e9e8125ffa12be9ed039835d015893d5054/omniverse/extension/omni.viplanner/omni/viplanner/config/matterport_cfg.py#L52
matterport-stuck
matterport-falls
5. [docs fix] The link for the extension doesn't seem to be needed anymore.
https://github.com/leggedrobotics/viplanner/blob/d68a046a54877d3ed6c6c78e6fca618b0f23b106/README.md?plain=1#L83
6. [docs fix] please contact **~~the~~** us
https://github.com/leggedrobotics/viplanner/blob/d68a046a54877d3ed6c6c78e6fca618b0f23b106/omniverse/README.md?plain=1#L113

**Comment by fan-ziqi** [comment]
The material issue for the second problem has been resolved, and the solution is that the USD path must be an absolute path, but the robot still cannot walk properly.

**Comment by fan-ziqi** [comment]
I found that the robot uses `GroundPlane` as the reference plane for `height_scanner`, but it is still making contact with the uneven **green** terrain below the ground, causing the robot to fall.
GroundPlane
So I wonder if this process is incorrect?

**Comment by pascal-roth** [comment]
> I found that the robot uses `GroundPlane` as the reference plane for `height_scanner`, but it is still making contact with the uneven **green** terrain below the ground, causing the robot to fall. GroundPlane So I wonder if this process is incorrect?

no, thats not the same as the behavior in my local environment. I will update the online asset

**Comment by fan-ziqi** [comment]
Ok, I'll wait for your new model for testing.

> > I found that the robot uses `GroundPlane` as the reference plane for `height_scanner`, but it is still making contact with the uneven **green** terrain below the ground, causing the robot to fall. GroundPlane So I wonder if this process is incorrect?
> 
> no, thats not the same as the behavior in my local environment. I will update the online asset

**Comment by fan-ziqi** [comment]
As mentioned in issue #14 , I'm still unclear about how to prepare the data needed for training. Aside from that, I don’t have other questions for running the demo on my side. 
Due to the time difference, I will respond to your message or continue following up on the testing tomorrow. Wishing you a wonderful day!

**Comment by pascal-roth** [comment]
@fan-ziqi let me know if there are any new bugs for you, otherwise I merge it by the end of the day. Thanks again for your help

**Comment by fan-ziqi** [comment]
I discovered an issue and resolved it. Here’s the problem description and solution:

When using the `convert_mesh.py` script to convert `.obj` to `.usd`, if user uses the `2n8kARJN3HM` scene mentioned in README, the conversion will fail. 

```bash
Usd.Stage.Open(rootLayer=Sdf.Find('anon:0x23b593e0:tmp.usda'), sessionLayer=Sdf.Find('anon:0x23b3f000:tmp-session.usda'), pathResolverContext=<invalid repr>)
2024-10-22 11:14:00 [5,398ms] [Warning] [omni.usd] Warning: in SdfPath at line 81 of /builds/omniverse/usd-ci/USD/pxr/usd/sdf/path.cpp -- Ill-formed SdfPath </0c334eaabb844eaaad049cbbb2e0a4f2>: syntax error

Traceback (most recent call last):
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/../IsaacLab/source/standalone/tools/convert_mesh.py", line 177, in <module>
    main()
  File "/home/ubuntu/workspaces/viplanner_ws/viplanner/../IsaacLab/source/standalone/tools/convert_mesh.py", line 147, in main
    mesh_converter = MeshConverter(mesh_converter_cfg)
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 58, in __init__
    super().__init__(cfg=cfg)
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/asset_converter_base.py", line 104, in __init__
    self._convert_asset(cfg)
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 85, in _convert_asset
    asyncio.get_event_loop().run_until_complete(
  File "/home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/site-packages/omni/extscore/omni.kit.async_engine/omni/kit/async_engine/async_engine.py", line 160, in run_until_complete
    return self.super_run_until_complete(future)
  File "/home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 223, in _convert_mesh_to_usd
    base_prim = temp_stage.DefinePrim(prim_path, "Xform")
pxr.Tf.ErrorException: 
	Error in 'pxrInternal_v0_22__pxrReserved__::UsdStage::_IsValidPathForCreatingPrim' at line 3340 in file /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp : 'Path must be an absolute path: <>'
```

The reason is that the obj file in this scene starts with a number(`0c334eaabb844eaaad049cbbb2e0a4f2.obj`), while the USD API prohibits names that start with a number [Link](https://openusd.org/release/api/group__group__tf___string.html#gaa129b294af3f68d01477d430b70d40c8). This issue is described in more detail here: [Link](https://forums.developer.nvidia.com/t/cant-create-prims-if-name-starts-with-number/249617). 

I think it’s necessary to mention this in README, as the error message doesn’t indicate the underlying problem.

Perhaps we should inform the IsaacLab team to modify the `_convert_asset()` function in `convert_mesh.py` script to throw a user-friendly warning when the `mesh_file_basename` does not comply with the USD file format.

**Comment by pascal-roth** [comment]
> I discovered an issue and resolved it. Here’s the problem description and solution:
> 
> 
> 
> When using the `convert_mesh.py` script to convert `.obj` to `.usd`, if user uses the `2n8kARJN3HM` scene mentioned in README, the conversion will fail. 
> 
> 
> 
> ```bash
> 
> Usd.Stage.Open(rootLayer=Sdf.Find('anon:0x23b593e0:tmp.usda'), sessionLayer=Sdf.Find('anon:0x23b3f000:tmp-session.usda'), pathResolverContext=<invalid repr>)
> 
> 2024-10-22 11:14:00 [5,398ms] [Warning] [omni.usd] Warning: in SdfPath at line 81 of /builds/omniverse/usd-ci/USD/pxr/usd/sdf/path.cpp -- Ill-formed SdfPath </0c334eaabb844eaaad049cbbb2e0a4f2>: syntax error
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/../IsaacLab/source/standalone/tools/convert_mesh.py", line 177, in <module>
> 
>     main()
> 
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/../IsaacLab/source/standalone/tools/convert_mesh.py", line 147, in main
> 
>     mesh_converter = MeshConverter(mesh_converter_cfg)
> 
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 58, in __init__
> 
>     super().__init__(cfg=cfg)
> 
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/asset_converter_base.py", line 104, in __init__
> 
>     self._convert_asset(cfg)
> 
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 85, in _convert_asset
> 
>     asyncio.get_event_loop().run_until_complete(
> 
>   File "/home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/site-packages/omni/extscore/omni.kit.async_engine/omni/kit/async_engine/async_engine.py", line 160, in run_until_complete
> 
>     return self.super_run_until_complete(future)
> 
>   File "/home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
> 
>     return future.result()
> 
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 223, in _convert_mesh_to_usd
> 
>     base_prim = temp_stage.DefinePrim(prim_path, "Xform")
> 
> pxr.Tf.ErrorException: 
> 
> 	Error in 'pxrInternal_v0_22__pxrReserved__::UsdStage::_IsValidPathForCreatingPrim' at line 3340 in file /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp : 'Path must be an absolute path: <>'
> 
> ```
> 
> 
> 
> The reason is that the obj file in this scene starts with a number(`0c334eaabb844eaaad049cbbb2e0a4f2.obj`), while the USD API prohibits names that start with a number [Link](https://openusd.org/release/api/group__group__tf___string.html#gaa129b294af3f68d01477d430b70d40c8). This issue is described in more detail here: [Link](https://forums.developer.nvidia.com/t/cant-create-prims-if-name-starts-with-number/249617). 
> 
> 
> 
> I think it’s necessary to mention this in README, as the error message doesn’t indicate the underlying problem.
> 
> 
> 
> Perhaps we should inform the IsaacLab team to modify the `_convert_asset()` function in `convert_mesh.py` script to throw a user-friendly warning when the `mesh_file_basename` does not comply with the USD file format.

Great find! We can make a note in the readme about it and make an issue in IsaacLab

**Comment by pascal-roth** [comment]
Any other issues you encountered?

**Comment by fan-ziqi** [comment]
Yes, I will send it out asap.

**Comment by fan-ziqi** [comment]
The conversion script generates two USD files: `*.usd` and `*_non_metric.usd`.

When I test using the `*.usd` file converted by the script, the robot keeps resetting infinitely (I have already followed the documentation to fix the coordinate system and scaling factors), which seems to be a bug. I haven't been able to find the cause of the issue.

https://github.com/user-attachments/assets/6d5c88da-9427-496e-b4a7-8dda49dbafa4

However, when I use the `*_non_metric.usd`, which is the original file, the robot runs correctly.

https://github.com/user-attachments/assets/35f38a6d-2c9d-4b4f-a404-5d90b6b7b56c

In addition, even if I don't fix the coordinate system and scaling factors after running the conversion script and simply save the file, the `*_non_metric.usd` still works fine. Therefore, I believe the 2nd step of the doc is unnecessary, users can directly use `*_non_metric.usd` file.

**Comment by pascal-roth** [comment]
In this case, the conversion function has been updated. Personally, I converted the assets a long time ago. I will add another node that the *_non_metric.usd should be used.

Thanks for investigating that.

**Comment by fan-ziqi** [comment]
After testing, on my side, there are no more bugs in the demo section so far. Below are the final recordings of the three scenes, which I hope can provide new users with some correct references.

## Matterport

https://github.com/user-attachments/assets/92b35336-a7f4-4809-b8ac-902821c181ef

## Carla

https://github.com/user-attachments/assets/3b7247f0-8bc8-44d8-baf0-2b3ab64f5199

## Warehouse

https://github.com/user-attachments/assets/92273916-1669-4ced-aae8-e9e83c3b260d

I think you can merge after fixing the above issues. 

Finally, thank you for your outstanding contributions to this project; it's been a pleasure collaborating with you.

**Comment by pascal-roth** [comment]
great, thank you so much. Fixed the rotation now.

**Comment by fan-ziqi** [comment]
> I discovered an issue and resolved it. Here’s the problem description and solution:
> 
> When using the `convert_mesh.py` script to convert `.obj` to `.usd`, if user uses the `2n8kARJN3HM` scene mentioned in README, the conversion will fail.
> 
> ```shell
> Usd.Stage.Open(rootLayer=Sdf.Find('anon:0x23b593e0:tmp.usda'), sessionLayer=Sdf.Find('anon:0x23b3f000:tmp-session.usda'), pathResolverContext=<invalid repr>)
> 2024-10-22 11:14:00 [5,398ms] [Warning] [omni.usd] Warning: in SdfPath at line 81 of /builds/omniverse/usd-ci/USD/pxr/usd/sdf/path.cpp -- Ill-formed SdfPath </0c334eaabb844eaaad049cbbb2e0a4f2>: syntax error
> 
> Traceback (most recent call last):
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/../IsaacLab/source/standalone/tools/convert_mesh.py", line 177, in <module>
>     main()
>   File "/home/ubuntu/workspaces/viplanner_ws/viplanner/../IsaacLab/source/standalone/tools/convert_mesh.py", line 147, in main
>     mesh_converter = MeshConverter(mesh_converter_cfg)
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 58, in __init__
>     super().__init__(cfg=cfg)
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/asset_converter_base.py", line 104, in __init__
>     self._convert_asset(cfg)
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 85, in _convert_asset
>     asyncio.get_event_loop().run_until_complete(
>   File "/home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/site-packages/omni/extscore/omni.kit.async_engine/omni/kit/async_engine/async_engine.py", line 160, in run_until_complete
>     return self.super_run_until_complete(future)
>   File "/home/ubuntu/anaconda3/envs/viplanner/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
>     return future.result()
>   File "/home/ubuntu/workspaces/viplanner_ws/IsaacLab/source/extensions/omni.isaac.lab/omni/isaac/lab/sim/converters/mesh_converter.py", line 223, in _convert_mesh_to_usd
>     base_prim = temp_stage.DefinePrim(prim_path, "Xform")
> pxr.Tf.ErrorException: 
> 	Error in 'pxrInternal_v0_22__pxrReserved__::UsdStage::_IsValidPathForCreatingPrim' at line 3340 in file /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp : 'Path must be an absolute path: <>'
> ```
> 
> The reason is that the obj file in this scene starts with a number(`0c334eaabb844eaaad049cbbb2e0a4f2.obj`), while the USD API prohibits names that start with a number [Link](https://openusd.org/release/api/group__group__tf___string.html#gaa129b294af3f68d01477d430b70d40c8). This issue is described in more detail here: [Link](https://forums.developer.nvidia.com/t/cant-create-prims-if-name-starts-with-number/249617).
> 
> I think it’s necessary to mention this in README, as the error message doesn’t indicate the underlying problem.
> 
> Perhaps we should inform the IsaacLab team to modify the `_convert_asset()` function in `convert_mesh.py` script to throw a user-friendly warning when the `mesh_file_basename` does not comply with the USD file format.

I've opened a issue here https://github.com/isaac-sim/IsaacLab/issues/1287

**Pull request merged**
